site_name: Pyproject-template Guide
site_author: Sioux
site_description: A python project template guide
copyright: Copyright &copy; 2023-2024 Sioux
repo_url: https://github.com/maxisioux/pyproject-template.git
repo_name: maxisioux/pyproject-template

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    # accent: orange
    second: grey
  logo: img/small-logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: img/small-logo.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

extra_css:
  - stylesheets/reference.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_if_no_docstring: true
            group_by_category: false

nav:
- Home: index.md
- Integrations:
    - Getting started: integrations/get_start.md
- Tutorials:
    - Poetry: tutorials/poetry.md
    - Pytest: tutorials/pytest.md
    - Ruff: tutorials/ruff.md
- About:
    - About: about/about.md
    - Release Notes: about/release-notes.md
    - License: about/license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maxisioux